theme: jekyll-theme-slate

# Site settings
title: Blog for thurian
email: oliver@forrtitvau.se
description: Worldbuilder # this means to ignore newlines until "baseurl:"
url: "" # the base hostname & protocol for your site
